export enum StateName {
  TurnEnd = 'TurnEnd',
  TurnStart = 'TurnStart',
  PreDiceRoll = 'PreDiceRoll',
  PostDiceRoll = 'PostDiceRoll',
  LandedOnTile = 'LandedOnTile',
  GameStart = 'GameStart',
  GameOver = 'GameOver',
  RollDice = 'RollDice',
  BuyProperty = 'BuyProperty',
  BuyBuilding = 'BuyBuilding',
  SellBuilding = 'SellBuilding',
  MortgageProperty = 'MortgageProperty',
  UnmortgageProperty = 'UnmortgageProperty',
}
